### ISSUE TITLE
Can not open dowloaded model file

### ISSUE THREAD

**Issue by RocketeerFly** [maierfelix/POGO-asset-downloader#1]
I've downloaded some pokemon models but can not open it (I used Sketchup on Mac OS). Could you tell me what is the model file's format?
Thanks!

**Comment by maierfelix** [comment]
See [here](https://www.reddit.com/r/pokemongodev/comments/4xh1gs/how_pokemon_3d_models_are_decrypted/)
This lib just downloads all platform dependant assets in binary format. However its possible to port the python script over to nodejs and embed it here.
